// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://carguessr.uk",
        "contact": {
            "name": "CarGuessr Support",
            "url": "https://github.com/your-repo/carguessr/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/cache-status": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "Returns information about the current cache status, age, and listing counts. Requires admin authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get cache status information (Admin Only)",
                "responses": {
                    "200": {
                        "description": "cache status information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized - Admin key required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/leaderboard-status": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "Returns information about the leaderboard file, entry counts, and storage details. Requires admin authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get leaderboard status information (Admin Only)",
                "responses": {
                    "200": {
                        "description": "leaderboard status information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized - Admin key required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/listings": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "Returns all car listings currently loaded in the system with full details including prices. This reveals all answers and is restricted to admin access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get all available car listings (Admin Only)",
                "responses": {
                    "200": {
                        "description": "count and cars array",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized - Admin key required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/refresh-listings": {
            "post": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "Triggers a non-blocking background refresh of car listings. Supports mode query param (bonhams/lookers/both). Requires admin authentication and has a 30-minute cooldown between requests. Game continues normally during refresh.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Manually refresh car listings (Admin Only)",
                "parameters": [
                    {
                        "enum": [
                            "bonhams",
                            "lookers",
                            "both"
                        ],
                        "type": "string",
                        "default": "both",
                        "description": "Refresh mode (bonhams, lookers, both)",
                        "name": "mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: refresh started, status: refreshing, note: game continues normally",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized - Admin key required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited or refresh cooldown active",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/test-scraper": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "description": "Tests the Bonhams scraper and returns up to 10 cars with full details. This is an expensive operation. Requires admin authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Test the car scraper directly (Admin Only)",
                "responses": {
                    "200": {
                        "description": "message, count, and cars array",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized - Admin key required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error and message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Authenticates a user with username and password. Returns a session token valid for 7 days. Automatically upgrades password hashes to current security standards.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login to an existing account",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create session",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "Invalidates the current session token and clears the session cookie. Can be called without authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout from current session",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile information including leaderboard statistics and rankings. Requires authentication via session token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "user: User object, leaderboardStats: rankings and stats",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows authenticated users to update their display name or avatar URL. Display names must be unique.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Profile update data",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "avatarUrl": {
                                    "type": "string"
                                },
                                "displayName": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile updated successfully",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "409": {
                        "description": "Display name already exists",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to update profile",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Creates a new user account with username, password, display name, and security question for password recovery. Password is hashed with bcrypt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user account",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "registration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Account created successfully",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data or validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "409": {
                        "description": "Username or display name already exists",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create user account",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/reset-password": {
            "post": {
                "description": "Resets a user's password by verifying their username, display name, and security question answer. Includes timing attack protection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset user password",
                "parameters": [
                    {
                        "description": "Password reset data",
                        "name": "reset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.PasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password reset successfully",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or security answer",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to update password",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/security-question": {
            "post": {
                "description": "Returns a user's security question after verifying their username and display name. Used for password reset flow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get security question for password reset",
                "parameters": [
                    {
                        "description": "Username and display name",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "displayName": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success: true, securityQuestion: string",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/challenge/start": {
            "post": {
                "description": "Starts a new 10-car challenge session with GeoGuessr-style scoring. Supports difficulty query param (easy/hard). Rate limited to 60 requests per minute per IP.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenge"
                ],
                "summary": "Start a new Challenge Mode session",
                "parameters": [
                    {
                        "enum": [
                            "easy",
                            "hard"
                        ],
                        "type": "string",
                        "description": "Difficulty mode (easy for Lookers, hard for Bonhams)",
                        "name": "difficulty",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "sessionId, cars array (10 cars with prices hidden), currentCar: 0, totalScore: 0",
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.ChallengeSession"
                        }
                    },
                    "404": {
                        "description": "error: Not enough cars available for challenge mode",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/challenge/{sessionId}": {
            "get": {
                "description": "Returns the current state of a challenge session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenge"
                ],
                "summary": "Get current challenge session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.ChallengeSession"
                        }
                    },
                    "404": {
                        "description": "error: Session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/challenge/{sessionId}/guess": {
            "post": {
                "description": "Submit a price guess for the current car in challenge mode. Returns points based on accuracy (max 5000 points). Rate limited to 60 requests per minute per IP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenge"
                ],
                "summary": "Submit a guess for challenge mode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge Session ID (16 alphanumeric characters)",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Price guess (max price: £10,000,000)",
                        "name": "guess",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.ChallengeGuessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "points earned, totalScore, isLastCar, message, originalUrl",
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.ChallengeResponse"
                        }
                    },
                    "400": {
                        "description": "error: Invalid request, session complete, or price exceeds maximum",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error: Session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/check-guess": {
            "post": {
                "description": "Submit a price guess and get feedback on accuracy, score, and game status. Rate limited to 60 requests per minute per IP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Submit a price guess for a car",
                "parameters": [
                    {
                        "description": "Price guess data (max price: £10,000,000)",
                        "name": "guess",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.GuessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.GuessResponse"
                        }
                    },
                    "400": {
                        "description": "error: Invalid request or price exceeds maximum",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error: Listing not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/data-source": {
            "get": {
                "description": "Returns information about both data sources (Bonhams and Lookers) including listing counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "debug"
                ],
                "summary": "Get current data source information",
                "responses": {
                    "200": {
                        "description": "data sources info with Easy/Hard mode listings",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/friends/challenges": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new multiplayer challenge with a unique 6-character code. The challenge includes 10 pre-selected cars that all participants will guess. Requires authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Create a new friend challenge",
                "parameters": [
                    {
                        "description": "Challenge creation data",
                        "name": "challenge",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.CreateFriendChallengeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "success, message, challenge, challengeCode, sessionId, participantCount, shareMessage",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request data or validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to create challenge",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/friends/challenges/my-challenges": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all challenges the authenticated user has created or is participating in. Requires authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Get user's challenges",
                "responses": {
                    "200": {
                        "description": "success, created (array), participating (array)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to get challenges",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/friends/challenges/{code}": {
            "get": {
                "description": "Returns challenge information including participants and their completion status. Public endpoint - no authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Get friend challenge details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge code (6 alphanumeric characters)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, challenge with participants",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid challenge code format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Challenge not found or expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to get participants",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/friends/challenges/{code}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows an authenticated user to join an existing challenge using the challenge code. Creates a new session with the same cars as the template.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Join a friend challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge code (6 alphanumeric characters)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, message, sessionId, challenge",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid code, already participating, challenge full, or expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Challenge not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to join challenge",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/friends/challenges/{code}/leaderboard": {
            "get": {
                "description": "Returns ranked list of all participants with their scores and completion status. Public endpoint - no authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Get challenge leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge code (6 alphanumeric characters)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, challenge, participants (ranked), totalCount",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid challenge code format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Challenge not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to get leaderboard",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/friends/challenges/{code}/participation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's participation details and session for a specific challenge. Requires authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Get user participation in challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Challenge code (6 alphanumeric characters)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, challenge, participation, session",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid challenge code format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Challenge not found or not participating",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to get session details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/leaderboard": {
            "get": {
                "description": "Returns the leaderboard optionally filtered by game mode and difficulty, sorted by score (descending for challenge, ascending for streak)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get the game leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game mode filter (streak or challenge)",
                        "name": "mode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Difficulty filter (easy or hard)",
                        "name": "difficulty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of entries to return (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/autotraderguesser_internal_models.LeaderboardEntry"
                            }
                        }
                    }
                }
            }
        },
        "/api/leaderboard/submit": {
            "post": {
                "description": "Submit a score to the leaderboard for streak or challenge mode. Validates the score against the session data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Submit a score to the leaderboard",
                "parameters": [
                    {
                        "description": "Score submission data",
                        "name": "submission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.LeaderboardSubmissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success message and leaderboard position",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error: Invalid request or score validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/random-enhanced-listing": {
            "get": {
                "description": "Returns a random car listing with full details, supports difficulty query param (easy/hard)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get a random car listing with all characteristics based on difficulty",
                "parameters": [
                    {
                        "enum": [
                            "easy",
                            "hard"
                        ],
                        "type": "string",
                        "description": "Difficulty mode (easy for Lookers, hard for Bonhams)",
                        "name": "difficulty",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.EnhancedCar"
                        }
                    },
                    "404": {
                        "description": "error: No listings available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/random-listing": {
            "get": {
                "description": "Returns a random car listing with the price hidden (set to 0) for the guessing game. Rate limited to 60 requests per minute per IP.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get a random car listing for the game",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/autotraderguesser_internal_models.EnhancedCar"
                        }
                    },
                    "404": {
                        "description": "error: No listings available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "error: Too Many Requests - Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "autotraderguesser_internal_models.ChallengeGuess": {
            "type": "object",
            "properties": {
                "actualPrice": {
                    "type": "number"
                },
                "carId": {
                    "type": "string"
                },
                "carIndex": {
                    "type": "integer"
                },
                "difference": {
                    "description": "Calculated field",
                    "type": "number"
                },
                "guessedPrice": {
                    "type": "number"
                },
                "percentage": {
                    "type": "number"
                },
                "points": {
                    "type": "integer"
                }
            }
        },
        "autotraderguesser_internal_models.ChallengeGuessRequest": {
            "type": "object",
            "required": [
                "guessedPrice"
            ],
            "properties": {
                "guessedPrice": {
                    "type": "number",
                    "maximum": 10000000,
                    "minimum": 0
                }
            }
        },
        "autotraderguesser_internal_models.ChallengeResponse": {
            "type": "object",
            "properties": {
                "actualPrice": {
                    "type": "number"
                },
                "carId": {
                    "type": "string"
                },
                "carIndex": {
                    "type": "integer"
                },
                "difference": {
                    "description": "Calculated field",
                    "type": "number"
                },
                "guessedPrice": {
                    "type": "number"
                },
                "isLastCar": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "nextCarNumber": {
                    "type": "integer"
                },
                "originalUrl": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "points": {
                    "type": "integer"
                },
                "sessionComplete": {
                    "type": "boolean"
                },
                "totalScore": {
                    "type": "integer"
                }
            }
        },
        "autotraderguesser_internal_models.ChallengeSession": {
            "type": "object",
            "properties": {
                "cars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autotraderguesser_internal_models.EnhancedCar"
                    }
                },
                "completedTime": {
                    "type": "string"
                },
                "currentCar": {
                    "type": "integer"
                },
                "difficulty": {
                    "type": "string"
                },
                "guesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autotraderguesser_internal_models.ChallengeGuess"
                    }
                },
                "isComplete": {
                    "type": "boolean"
                },
                "sessionId": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "totalScore": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "autotraderguesser_internal_models.CreateFriendChallengeRequest": {
            "type": "object",
            "required": [
                "difficulty",
                "title"
            ],
            "properties": {
                "difficulty": {
                    "type": "string",
                    "enum": [
                        "easy",
                        "hard"
                    ]
                },
                "maxParticipants": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 2
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "autotraderguesser_internal_models.EnhancedCar": {
            "type": "object",
            "properties": {
                "auctionDetails": {
                    "description": "Flag indicating this is auction data",
                    "type": "boolean"
                },
                "bodyColour": {
                    "type": "string"
                },
                "bodyType": {
                    "type": "string"
                },
                "description": {
                    "description": "Combined description",
                    "type": "string"
                },
                "doors": {
                    "type": "string"
                },
                "emissionClass": {
                    "type": "string"
                },
                "engine": {
                    "type": "string"
                },
                "exteriorColor": {
                    "description": "More detailed color",
                    "type": "string"
                },
                "fuelType": {
                    "type": "string"
                },
                "fullTitle": {
                    "description": "Complete original title for Easy mode",
                    "type": "string"
                },
                "gearbox": {
                    "type": "string"
                },
                "id": {
                    "description": "Standard Car fields",
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "interiorColor": {
                    "description": "Interior details",
                    "type": "string"
                },
                "keyFacts": {
                    "description": "Auction key facts",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "description": "Vehicle location e.g. \"Bournemouth, Dorset, United Kingdom\"",
                    "type": "string"
                },
                "make": {
                    "type": "string"
                },
                "mileage": {
                    "description": "Standard overview fields",
                    "type": "integer"
                },
                "mileageFormatted": {
                    "description": "Enhanced Bonhams fields",
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "originalUrl": {
                    "type": "string"
                },
                "owners": {
                    "type": "string"
                },
                "price": {
                    "description": "Will be 0 for guessing",
                    "type": "number"
                },
                "registration": {
                    "type": "string"
                },
                "saleDate": {
                    "description": "Sale date in format \"29 Jul 2025\"",
                    "type": "string"
                },
                "seats": {
                    "type": "string"
                },
                "steering": {
                    "description": "\"Right-hand drive\"",
                    "type": "string"
                },
                "trim": {
                    "description": "Enhanced Lookers fields",
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "autotraderguesser_internal_models.GuessRequest": {
            "type": "object",
            "required": [
                "gameMode",
                "guessedPrice",
                "listingId"
            ],
            "properties": {
                "difficulty": {
                    "description": "Default to hard for backward compatibility",
                    "type": "string",
                    "enum": [
                        "easy",
                        "hard"
                    ]
                },
                "gameMode": {
                    "type": "string",
                    "enum": [
                        "zero",
                        "streak",
                        "challenge"
                    ]
                },
                "guessedPrice": {
                    "type": "number",
                    "maximum": 10000000,
                    "minimum": 0
                },
                "listingId": {
                    "type": "string"
                }
            }
        },
        "autotraderguesser_internal_models.GuessResponse": {
            "type": "object",
            "properties": {
                "actualPrice": {
                    "type": "number"
                },
                "correct": {
                    "type": "boolean"
                },
                "difference": {
                    "type": "number"
                },
                "gameOver": {
                    "type": "boolean"
                },
                "guessedPrice": {
                    "type": "number"
                },
                "message": {
                    "type": "string"
                },
                "originalUrl": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "autotraderguesser_internal_models.LeaderboardEntry": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "date": {
                    "description": "Formatted date for JSON response",
                    "type": "string"
                },
                "difficulty": {
                    "description": "\"easy\" or \"hard\", defaults to \"hard\" for backward compatibility",
                    "type": "string"
                },
                "friendChallengeId": {
                    "type": "integer"
                },
                "gameMode": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "legacyId": {
                    "description": "For migration from JSON",
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                },
                "score": {
                    "type": "integer"
                },
                "sessionId": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "autotraderguesser_internal_models.LeaderboardSubmissionRequest": {
            "type": "object",
            "required": [
                "gameMode",
                "name",
                "score"
            ],
            "properties": {
                "difficulty": {
                    "description": "Default to hard for backward compatibility",
                    "type": "string",
                    "enum": [
                        "easy",
                        "hard"
                    ]
                },
                "gameMode": {
                    "type": "string",
                    "enum": [
                        "streak",
                        "challenge"
                    ]
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                },
                "score": {
                    "type": "integer",
                    "minimum": 0
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "autotraderguesser_internal_models.PasswordResetRequest": {
            "type": "object",
            "required": [
                "displayName",
                "newPassword",
                "securityAnswer",
                "username"
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string",
                    "minLength": 6
                },
                "securityAnswer": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "autotraderguesser_internal_models.User": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "favoriteDifficulty": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isGuest": {
                    "type": "boolean"
                },
                "lastActive": {
                    "type": "string"
                },
                "securityQuestion": {
                    "type": "string"
                },
                "sessionToken": {
                    "type": "string"
                },
                "totalGamesPlayed": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.AuthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sessionToken": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/autotraderguesser_internal_models.User"
                }
            }
        },
        "internal_handlers.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.RegisterRequest": {
            "type": "object",
            "required": [
                "displayName",
                "password",
                "securityAnswer",
                "securityQuestion",
                "username"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "securityAnswer": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "securityQuestion": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminKey": {
            "description": "Admin API key required for administrative endpoints. Can also be passed as 'admin_key' query parameter.",
            "type": "apiKey",
            "name": "X-Admin-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "CarGuessr API",
	Description:      "A fun car price guessing game with multiple game modes using real Bonhams Car Auction data. Now with enhanced security, rate limiting, and 250 cars with 7-day refresh cycles.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
